<?php

/**
 * @file
 * Module for displaying your latest Forrst posts.
 *
 * @see http://www.forrst.com
 */

/**
 * Display help and module information
 * 
 * @param path which path of the site we're displaying help
 * @param arg array that holds the current path as would be returned from arg() function
 * @return help text for the path
 */
function forrst_help($path, $arg) {
  $output = '';
  switch ($path) {
    case "admin/help#forrst":
      $output = '<p>' . t('Display your latest Forrst posts on your Drupal website.') . '</p>';
      break;
  }

  return $output;
}

/**
 * Implementation of hook_perm()
 */
function forrst_perm() {
  return array('administer Forrst');
}

/**
 * Implementation of hook_menu()
 */
function forrst_menu() {
  $items = array();

  $items['admin/settings/forrst'] = array(
    'title' => 'Forrst',
    'description' => 'Configure settings for the Forrst module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('forrst_settings'),
    'access arguments' => array('administer Forrst'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Forrst Settings page
 *
 * @return settings form
 */
function forrst_settings() {
  $form = array();

  $form['forrst_username'] = array(
    '#type' => 'textfield',
    '#title' => t('UserName'),
    '#default_value' => variable_get('forrst_username', 'forrst'),
    '#size' => 50,
    '#maxlength' => 255,
    '#description' => t('Your Forrst Username'), 
  );

  $form['forrst_no_of_posts'] = array(
    '#type' => 'select',
    '#title' => t('No. of Posts'),
    '#default_value' => variable_get('forrst_no_of_posts', '1'),
    '#options' => array("1" => "1", "2" => "2", "3" => "3"),
    '#description' => t('No. of Forrst posts to display.'), 
  );
  
  $form['forrst_include_css'] = array(
    '#type' => 'select',
    '#title' => t('Include CSS?'),
    '#default_value' => variable_get('forrst_include_css', '1'),
    '#options' => array(1 => "Yes", 0 => "No"),
    '#description' => t('Whether or not to use the included stylesheet.'), 
  );

  return system_settings_form($form);
}
